/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ReunionTypes, } from "./utils/constants";
export namespace Components {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface CountdownClock {
        "goToLink": () => Promise<void>;
        "reunionDate": string;
        "reunionDuration": number;
        "reunionLink": string;
        "reunionType": ReunionTypes;
        "stopTimer": () => Promise<void>;
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLCountdownClockElement extends Components.CountdownClock, HTMLStencilElement {
    }
    var HTMLCountdownClockElement: {
        prototype: HTMLCountdownClockElement;
        new (): HTMLCountdownClockElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
        "countdown-clock": HTMLCountdownClockElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface CountdownClock {
        "reunionDate"?: string;
        "reunionDuration"?: number;
        "reunionLink"?: string;
        "reunionType"?: ReunionTypes;
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-root": AppRoot;
        "countdown-clock": CountdownClock;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "countdown-clock": LocalJSX.CountdownClock & JSXBase.HTMLAttributes<HTMLCountdownClockElement>;
        }
    }
}
